[project]
name = "robojira-cli"
version = "0.8.0"
description = "A CLI tool for Jira automation"
readme = "README.md"
authors = [{name = "Maksym Biriukov", email = "maximbirukov77@gmail.com"}]
requires-python = ">=3.9,<3.13"
dependencies = [
    "httpx>=0.28.1",
    "xlsxwriter>=3.1.9",
]

[project.scripts]
robojira = "robojira_cli.cli:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
